<?php
/**
 * Laravel-Env-Sync
 *
 * @author Julien Tant - Craftyx <julien@craftyx.fr>
 */

namespace Jtant\LaravelEnvSync;

use File;
use Jtant\LaravelEnvSync\Reader\EnvFileReader;
use Jtant\LaravelEnvSync\Reader\ReaderInterface;
use Mockery\Mock;
use org\bovigo\vfs\vfsStream;
use Symfony\Component\Console\Output\OutputInterface;

class SyncServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SyncService
     */
    private $sync;

    protected function tearDown()
    {
        \Mockery::close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_return_the_difference_between_files()
    {
        $root = vfsStream::setup("sync_service");
        $source = $root->url() . '/source';
        $destination = $root->url() . '/dest';
        touch($source);
        touch($destination);


        $readerInterface = \Mockery::mock(ReaderInterface::class)
            ->shouldReceive('read')->twice()->andReturn([
                "foo" => "bar",
                "baz" => "foo",
            ], [
                "foo" => "bar",
                "bar" => "baz",
                "baz" => "foo"
            ]);

        $sync = new SyncService($readerInterface->getMock());


        $result = $sync->getDiff($source, $destination);

        $this->assertEquals([
            'bar' => 'baz'
        ], $result);
    }

    /** @test */
    public function it_should_throw_an_exception_if_file_are_not_found()
    {
        $root = vfsStream::setup("sync_service");
        $source = $root->url() . '/source';
        $destination = $root->url() . '/dest';
        touch($source);
        touch($destination);


        $readerInterface = \Mockery::mock(ReaderInterface::class)
            ->shouldReceive('read')->twice()->andReturn([
                "foo" => "bar",
                "baz" => "foo",
            ], [
                "foo" => "bar",
                "bar" => "baz",
                "baz" => "foo"
            ]);

        $sync = new SyncService($readerInterface->getMock());



        $result = $sync->getDiff($source, $destination);

        $this->assertEquals([
            'bar' => 'baz'
        ], $result);


    }
}
